services:
  char-art-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # 此处变量会覆盖.env和.env.production中的变量，为空时使用.env和.env.production中的变量
        # 资源路径前缀，可选，不填写则使用.env.production中的变量，填写时不要带上前后斜杠
        - VITE_BASE_PATH=
        # 后端地址，可选，不填写则使用.env.production中的变量，填写时带上http://
        - VITE_API_URL=http://localhost:8080
    container_name: char-art-frontend
    ports:
      - "8080:80"
#    environment:
      # 修改环境变量，请修改.env和.env.production中的变量，再重新制作镜像，此处修改无用，仅做示例
      # Vite环境变量
      # - VITE_BASE_PATH=char-art
      # - VITE_API_URL=http://char-art-backend:8080
      # - VITE_API_BASE_PATH=/api
      # - VITE_MAX_UPLOAD_SIZE=10
    restart: unless-stopped
    networks:
      - char-art-network

networks:
  char-art-network:
    driver: bridge
    # 如果需要与后端服务共用网络，请取消下面的注释并确保网络名称一致
    external: true
    name: char-art-network