version: '3.8'

services:
  char-art-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: char-art-frontend
    ports:
      - "8080:80"
    environment:
      # Vite环境变量
      - VITE_BASE_PATH=char-art
      - VITE_API_URL=http://char-art-backend:8080
      - VITE_API_BASE_PATH=/api
      - VITE_MAX_UPLOAD_SIZE=10
      # 兼容旧版本的环境变量
      - BASE_PATH=char-art
      - API_URL=http://char-art-backend:8080
      - MAX_UPLOAD_SIZE=10
    restart: unless-stopped
    networks:
      - char-art-network

networks:
  char-art-network:
    driver: bridge
    # 如果需要与后端服务共用网络，请取消下面的注释并确保网络名称一致
    external: true
    name: char-art-network