services:
  # 字符画转换器一体化服务
  char-art-converter-full:
    image: char-art-converter-full:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # 此处变量会覆盖.env和.env.production中的变量，为空时使用.env和.env.production中的变量
        # 资源路径前缀，可选，默认为空，填写时不要带上前后斜杠
        - VITE_BASE_PATH=charartconverter
    container_name: full-service
    ports:
      - "9582:80"      # 前端服务
    environment:
      # 时区，默认为亚洲/上海
      - TIMEZONE=Asia/Shanghai
    volumes:
      - char-art-data:/app/backend/data
      - char-art-logs:/app/backend/logs
      - webp-processor-data:/app/webp-processor/data
      - webp-processor-logs:/app/webp-processor/logs
    restart: unless-stopped
    networks:
      - char-art-network-full

networks:
  char-art-network-full:
    driver: bridge

volumes:
  char-art-data:
  char-art-logs:
  webp-processor-data:
  webp-processor-logs: