version: '3.8'

services:
  # WebP处理服务
  webp-processor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webp-processor
    ports:
      - "8081:5000"
    environment:
      # 服务配置
      - PORT=5000
      - LOG_LEVEL=INFO
      - DEBUG=False
      - MAX_CONTENT_LENGTH=16777216
      - TEMP_FILE_TTL=3600
      # Gunicorn配置
      - GUNICORN_WORKERS=4  # 工作进程数，建议设置为CPU核心数×2+1
      - GUNICORN_TIMEOUT=120  # 请求超时时间(秒)
      - GUNICORN_MAX_REQUESTS=1000  # 每个工作进程处理的最大请求数
      - GUNICORN_MAX_REQUESTS_JITTER=50  # 最大请求数的随机抖动值
    volumes:
      - webp-processor-data:/app/data
      - webp-processor-logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - char-art-network

networks:
  char-art-network:
    driver: bridge
    # 如果需要与后端服务共用网络，请取消下面的注释并确保网络名称一致
    external: true
    name: char-art-network

volumes:
  webp-processor-data:
  webp-processor-logs: